'use client';

import type { Metadata } from "next";
import { Provider } from "react-redux"; // Se agrega el proveedor de Redux
import { store } from "../redux/store"; 
import "./globals.css";

import FavoritosFloating from './components/FavoritosFloating';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        {/* Se envuelve la aplicación en el proveedor de Redux para gestionar el estado global */}
        <Provider store={store}>
          {children}

          {/* Componente que usa useSelector */}
          <FavoritosFloating />
        </Provider>
      </body>
    </html>
  );
}
