// src/app/layout.tsx
import type { Metadata } from "next";
import ReduxProviderWrapper from './components/ReduxProviderWrapper';
import FavoritosFloating from './components/FavoritosFloating';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReduxProviderWrapper>
          {children}
          <FavoritosFloating />
        </ReduxProviderWrapper>
      </body>
    </html>
  );
}
